config/routes.rb
Rails.application.routes.draw do
  
  get 'workouts/index' => 'workouts#index'
  get "exercises/index" => "exercises#index"
  get 'sessions/new'
  root to: 'pages#home'
  get 'pages/home'
  get "pages/mypage" => "pages#mypage"
  get "exercises/destroy",  to: "exercises#destroy"
  post "exercises/destroy",  to: "exercises#destroy"
  get  "workouts/diary", to: "workouts#diary"
  get "workouts/chart", to: "workouts#chart"
  
  resource :users
  resource :workouts
  resource :exercises
  resource :profiles
  resource :menus
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
  has_many :exercises
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :body_id, presence: true
  
  has_many :workouts
  belongs_to :body
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :weight, presence: true
  validates :rep, presence: true, numericality: {
             only_integer: true, greater_than: 0 }
  validates :set_count, presence: true, numericality: {
             only_integer: true, greater_than: 0 }
  
  
  belongs_to :workout
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , length: { maximum: 15 }
  validates :email, presence: true , uniqueness: true ,
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
             
  validates :password, presence: true,  
             format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }
  
             
  has_secure_password  
  
  has_one :profile
  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :exercise_id, presence: true
  validates :date, presence: true
  validates :user_id, presence: true
  
  has_many :menus
  belongs_to :user
  belongs_to :exercise
  
  accepts_nested_attributes_for :menus, allow_destroy: true

end

app/controllers/body_controller.rb
class BodyController < ApplicationController
  def new
    @body = Body.new
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def mypage
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  
  def create
    @user = User.new(user_params)
    
   if @user.save
     flash[:success] = '登録が完了しました'
     redirect_to root_path
   else
     flash[:danger] = '登録に失敗しました'
     render new_users_path
   end
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email,:password, :password_confirmation)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  
  def index
    @bodies = Body.all
    @exercises = Exercise.all
    @workouts = Workout.all
    @menus = Menu.all
  end
  
  def new
    @workout = Workout.new
    @workout.menus.build
  end
  
  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      redirect_to new_workouts_path, success: 'ワークアウトを記録しました'
    else
      flash.now[:danger] = "ワークアウトの記録に失敗しました"
      render :new
    end
  end
  
  
  def diary
    #テーブル結合部分#
    @workouts1 = Workout.joins(:menus).select("workouts.*,menus.*")
    @workouts2 = @workouts1.joins(:exercise).select("exercises.*,workouts.*,menus.*")
    
    
    if params.has_key?(:date)
      diary_date = Date.new params[:date]["{:class=>\"date-select\"}(1i)"].to_i,
                    params[:date]["{:class=>\"date-select\"}(2i)"].to_i,
                    params[:date]["{:class=>\"date-select\"}(3i)"].to_i
    else 
      diary_date = nil
    end
    #日付で検索
    @workout_diary = @workouts2.where(date: diary_date)
    @day = diary_date
    
    #二次元配列のロジック
    results = {}
    @workout_diary.each do |workout|
      # ハッシュの初期化
      results[workout.name] = [] if results[workout.name].nil?
      # 下記の << は要素resultsが空だとエラーになるため上記if文が必要
      results[workout.name] << { "set_count" => workout.set_count, "weight" => workout.weight, "rep" => workout.rep, "note" => workout.note }
    end
    
    @results = results
    
  end


  def chart
    #テーブルの結合
    @workouts3 = Workout.joins(:menus).select("workouts.*,menus.*")
    @workouts4 = @workouts3.joins(:exercise).select("exercises.*,workouts.*,menus.*")
    
    #種目入力によるワークアウトの絞り込み
    @workout_chart = @workouts4.where(exercise_id: params[:exercise_id])
    
    #グラフに渡す種目名の定義
    #if文にしないと他のページから飛んできたときエラーになる。
    if params.has_key?(:exercise_id)
      exercise = Exercise.find_by(id: params[:exercise_id])
      exercise_name = exercise.name
    else
      exercise_name = nil
    end
    gon.exercise_name = exercise_name
    
    
    #ワークアウトの日付(横軸)
    if params.has_key?(:exercise_id)
      #空の配列を用意
      workout_date = []
      @workout_chart.each do |workout_chart|
        workout_date << "#{workout_chart.date}　#{workout_chart.set_count}セット目"
      end
    else
      workout_date = nil
    end
    gon.workout_date = workout_date
    
    #１RMの重量(縦軸)
    if params.has_key?(:exercise_id)
      #空の配列を用意
      rm_weight = []
      @workout_chart.each do |workout_weight|
        #coefficientはRMを求める係数
        coefficient = 1 + (workout_weight.rep/40.to_f) 
        rm_weight << (workout_weight.weight) * coefficient
        #グラフの最小値、最大値
        gon.min = rm_weight.min - 2.5
        gon.max = rm_weight.max + 2.5
      end
    else
      rm_weight = nil
      gon.min = nil
      gon.max = nil
    end
    #RMの配列
    gon.rm_weight = rm_weight
    
  end


  
  
  private
  def workout_params
    params.require(:workout).permit(:date, :exercise_id, :user_id, menus_attributes: [:set_count, :weight, :rep, :note])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_helper.rb
module BodyHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/chart.html.erb
<div class="workout-chart-wrapper">
  <div class="container workout-chart-container">
    <h3>種目を入力してください</h3>
    <div class="row col-md-offset-4">
      <%= form_tag({controller: :workouts, action: :chart},:method => 'get') do %>
        <%= label_tag :id, "種目名", class: "label" %>
        <%= collection_select(@exercise, :exercise_id, Exercise.all, :id, :name, :prompt => true) %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    
    <!--文字列による記録-->
    <div class="row">
      <div class="col-md-offset-3 col-md-6 workout-menu">
         <%  @workout_chart.each do |workout| %>
           <%=  workout.date %> &nbsp;
           <%= "#{workout.set_count}セット目" %> &nbsp;
           <%= "#{workout.weight}kg" %> &nbsp;
           <%= "#{workout.rep}回" %> &nbsp;
           <%= workout.note %><br>
         <% end %>
         
         
       </div>
     </div>
    
    
    <!--グラフの組み込み-->
    <canvas id="myChart" width="100" height="100"></canvas>
    <script>draw_graph();</script>
    
    
  </div>
</div>

app/views/workouts/diary.html.erb
<div class="workout-diary-wrapper">
  <div class="container workout-diary-container">
    <h3>日付を入力してください</h3>
    <div class="row col-md-offset-4">
      <%= form_tag({controller: :workouts, action: :diary},:method => 'get') do %>
        <%= date_select :date, class: "date-select" %> 
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    
    
  
     <div class="row">
       <div class="col-md-offset-3 col-md-6 workout-menu">
         <%= @day %>
         
         <%  @results.each do |exercise_name, menu_lists| %>
         <h6>----------------------------------------------------------------------</h6>
           <%= "<#{exercise_name}>" %> <br>
           <% menu_lists.each do |menu| %>
           <%= "#{menu["set_count"]}セット目" %> &nbsp;
           <%= "#{menu["weight"]}kg" %> &nbsp;
           <%= "#{menu["rep"]}回" %> &nbsp;
           <%= menu["note"]%><br>
           <% end %>
         <% end %>
         
         
       </div>
     </div>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="workout-index-wrapper">
  <div class="container workout-index-container">
    <h1>ワークアウト内容を確認する</h1>
    <!--日別確認ページへのリンク-->
    <div class="col-md-offset-2 col-md-4">
      <%= link_to '日別で確認する', workouts_diary_path , class: 'btn btn-block btn-blue' %>
    </div>
      <!--種目別確認ページへのリンク-->
    <div class="col-md-4">
      <%= link_to '種目別で確認する', workouts_chart_path ,class: 'btn btn-block btn-blue' %>
    </div>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="workout-new-wrapper">
  <div class="container workout-new-container">
    <h1 class="text">ワークアウトを記録する</h1>
      <%= form_for @workout do |f| %>
        <!--日付入力フォーム-->      
        <div class="row">
          <div class="col-md-offset-4 col-md-4 date-form">
            <%= f.label :date, "日付" ,class:"label" %>
            <%= f.date_select :date, class: "date-select" %>
            <!--user_idを飛ばす-->
            <%= f.hidden_field :user_id, value: current_user.id %>
          </div>
        </div>    
        <!--種目入力-->
        <div class="row">
          <div class="col-md-offset-4 col-md-4 exercise-form">
            <%= f.label :exercise_id, "種目名", class: "label" %>
            <%= f.collection_select :exercise_id, Exercise.all, :id, :name, :prompt => true %>
          </div>
        </div>
        
        <!--Menu入力　これを１つのまとまりに-->
        <%= f.nested_fields_for :menus do |ff| %>
          <!--セット数-->
          <div class="row">
            <div class="col-md-offset-4 col-md-4">
              <%= ff.label :set_count, "セット", class:"label" %>
              <%= ff.number_field :set_count, class:"set-form" %>
            </div>
          </div>
          <!--重量-->
          <div class="row">
            <div class="col-md-offset-4 col-md-4">
              <%= ff.label :weight, "重　さ", class:"label" %>
              <%= ff.number_field :weight, class:"weight-form" %>
            </div>
          </div>
          <!--回数-->
          <div class="row">
            <div class="col-md-offset-4 col-md-4">
              <%= ff.label :rep, "回　数", class:"label" %>
              <%= ff.number_field :rep, class:"rep-form" %>
            </div>
          </div>  
          <!--メモ-->
          <div class="row">
            <div class="col-md-offset-4 col-md-4">
              <%= ff.label :note, "メ　モ", class:"note-label" %>
              <%= ff.text_field :note, class:"note-form", autocomplete: 'off' %>
              <!--削除ボタン-->
              <%= ff.remove_nested_fields_link '-', class: 'btn btn-danger', role: 'button' %>
            </div>
          </div>
        <% end %> 
        <!--追加ボタン-->
        <span><%= f.add_nested_fields_link :menus, '+', class: 'btn btn-primary add-button', role: 'button'  %></span>
        <!--記録ボタン-->  
        <div class="row">  
          <div class="col-md-offset-4 col-md-4 add-btn">
            <% if logged_in? %>
            <%= f.submit '記録', class: 'btn-block btn-blue' %>
            <% end %>
          </div>
        </div>  
      <% end %> 
  </div>
</div>