config/routes.rb
Rails.application.routes.draw do
  
  get 'workouts/index' => 'workouts#index'
  get "exercises/index" => "exercises#index"
  get 'sessions/new'
  root to: 'pages#home'
  get 'pages/home'
  get "pages/mypage" => "pages#mypage"
  get "exercises/destroy",  to: "exercises#destroy"
  post "exercises/destroy",  to: "exercises#destroy"
  get  "workouts/diary", to: "workouts#diary"
  get "workouts/chart", to: "workouts#chart"
  
  resource :users
  resource :workouts
  resource :exercises
  resource :profiles
  resource :menus
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
  has_many :exercises
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :body_id, presence: true
  
  has_many :workouts
  belongs_to :body
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :weight, presence: true
  validates :rep, presence: true, numericality: {
             only_integer: true, greater_than: 0 }
  validates :set_count, presence: true, numericality: {
             only_integer: true, greater_than: 0 }
  
  
  belongs_to :workout
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true , length: { maximum: 15 }
  validates :email, presence: true , uniqueness: true ,
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
             
  validates :password, presence: true,  
             format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }
  
             
  has_secure_password  
  
  has_one :profile
  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :exercise_id, presence: true
  validates :date, presence: true
  validates :user_id, presence: true
  
  has_many :menus
  belongs_to :user
  belongs_to :exercise
  
  accepts_nested_attributes_for :menus, allow_destroy: true

end

app/controllers/body_controller.rb
class BodyController < ApplicationController
  def new
    @body = Body.new
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_helper.rb
module BodyHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WoRec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
　　
　　<% if logged_in? %>
　  <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span class="header-logo"> WoRec </span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <li><!--マイページタブ-->
            <%= link_to pages_mypage_path do %>
              <span>マイページ</span>
            <% end %>
          </li>
          <li><!--記録タブ-->
            <%= link_to new_workouts_path do %>
              <span>ワークアウトを記録</span>
            <% end %>
          </li>
          <li><!--ワークアウト一覧タブ-->
            <%= link_to workouts_index_path do %>
              <span>ワークアウト内容を見る</span>
            <% end %>
          </li>
          <li><!--種目追加タブ-->
            <%= link_to  new_exercises_path do %>
              <span>種目追加</span>
            <% end %>
          </li> 
          <li><!--種目一覧タブ-->
            <%= link_to  exercises_index_path do %>
              <span>種目一覧</span>
            <% end %>
          </li>
          <li><!--ログアウトタブ-->
            <%= link_to logout_path, method: :delete do %>
              <span>ログアウト</span>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
　　<% end %>
　　
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-hero-wrapper text-center">
  <div class="container home-hero-container">
    <h1 class="text">Welcome to WoRec</h1>
    <h2 class="text">WoRecは日々のワークアウトの内容を記録するアプリケーションです</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '新規登録', new_users_path , class: 'btn btn-block btn-blue' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ログイン', login_path ,class: 'btn btn-block btn-blue' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/mypage.html.erb
<div class="users-mypage-wrapper">
  <div class="container mypage-container">
    <h1>My Page</h1>
    <div class="row">
      <!--ワークアウト記録ページへのリンク-->
      <div class="col-md-3">
        <%= link_to 'ワークアウトを記録する', new_workouts_path , class: 'btn btn-block btn-blue' %>
      </div>
      <!--ワークアウト閲覧ページへのリンク-->
      <div class="col-md-3">
        <%= link_to 'ワークアウト内容を見る', "/workouts/index" ,class: 'btn btn-block btn-blue' %>
      </div>
      <!--ワークアウトを追加する-->
      <div class="col-md-3">
        <%= link_to '種目を追加', new_exercises_path ,class: 'btn btn-block btn-blue' %>
      </div>
      <!--ワークアウト種目を確認する-->
      <div class="col-md-3">
        <%= link_to '種目一覧', "/exercises/index" ,class: 'btn btn-block btn-blue' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li class='error_messages'><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>